sudo: required

language: node_js
node_js: "8"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

install:
  - npm set progress=false
  - npm install -g netlify-cli
  - npm install

script:
  - npm run download-template
  - npm run build
  - npm run deploy